### ISSUE TITLE
Обернуть основные классы движка для использования в Python

### ISSUE THREAD

**Issue by Siriuscoder** [Siriuscoder/3dlite#49]
Разработать модуль для питона и примерчик который бы его использовал, нужно обернуть основные cpp классы движка, На первом этапе попробуем обернуть:

- lite3dpp::Scene
- lite3dpp::SceneObject
- lite3dpp::SceneNode
- lite3dpp::Camera
- lite3dpp::Main (Главный класс движка)
- lite3dpp::ResourceManager
- lite3dpp::RenderTarget

Этого хватит для загрузки сцены и манипулирования обьектами. Нужно решить что использовать в качестве библиотеки линейной алгебры. Существующую библиотеку оборачивать не надо, думаю на питоне есть куча эффективных решений. Вопросы сюда)

**Comment by nshibalov** [comment]
Для математики можно использовать NumPy.
